### ISSUE TITLE
Continuous Integration needs to set up

### ISSUE THREAD

**Issue by pao-pipat** [4the-right-side/pkmodel#2]

**Comment by pao-pipat** [comment]
@Pinguinus347

**Comment by Pinguinus347** [comment]
@anitaapplegarth Could you please approve access to Codecov for CI?
Hello, could you help approve the installation of the Codecov app on GitHub for our organization? Here's the link: https://github.com/apps/codecov/installations/select_target

**Comment by Pinguinus347** [comment]
Continuous integration functional for different operating systems and code coverage of Pytest
